language: php

php:
  - 5.3

branches:
  only:
    - 7.x-1.x

mysql:
  database: factorydrone_test
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # create new site
  - mysql -e 'create database factorydrone_test'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/factorydrone_test --enable=simpletest factorydrone_test

  # reference and enable factorydrone in build site
  - ln -s $(readlink -e $(cd -)) factorydrone_test/drupal/sites/all/modules/factorydrone
  - cd factorydrone_test/drupal
  - drush --yes pm-enable factorydrone

script: drush test-run 'Factory Drone'
